name: easy_track
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # UI
  flutter_screenutil: ^5.5.3+2

  # Local storage
  sqflite: ^2.0.2+1

  #Routing
  auto_route: ^4.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  auto_route_generator: ^4.2.0

flutter:

  uses-material-design: true

